---
abstract: 'Helper module for generating class definitions'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110420'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EntityModel-Class
requires:
  DateTime: 0
  DateTime::Format::Strptime: 0
  EntityModel::Log: 0.001
  Exporter: 0
  IO::Handle: 0
  List::Util: 0
  Tie::Cache::LRU: 0
  Time::HiRes: 0
  Try::Tiny: 0
  parent: 0
  perl: 5.010
version: 0.006
