---
abstract: 'Helper module for generating class definitions'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Test::Deep: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EntityModel-Class
requires:
  Check::UnitCheck: 0.13
  EntityModel::Log: 0.004
  Exporter: 0
  IO::Handle: 0
  List::Util: 0
  Mixin::Event::Dispatch: 1.000
  Try::Tiny: 0
  parent: 0
  perl: 5.010
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=EntityModel-Class
  homepage: http://search.cpan.org/dist/EntityModel-Class/
version: 0.013
